FROM hyperledger/iroha:1.1.0

LABEL author="Konrad Baechler <konrad@diva.exchange>" \
  maintainer="Konrad Baechler <konrad@diva.exchange>" \
  name="diva.iroha" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://diva.exchange"

COPY data-genesis/* /opt/iroha/data/
COPY entrypoint-genesis.sh wait-for-it.sh /

RUN apt-get update \
  && apt-get install -y \
    nano \
    iputils-ping \
  && mkdir -p "/opt/iroha/blockstore" \
  && chmod +x /entrypoint-genesis.sh /wait-for-it.sh

VOLUME [ "/opt/iroha/" ]
WORKDIR "/opt/iroha/data/"
ENTRYPOINT ["/entrypoint-genesis.sh"]
